# Generated by Django 4.1.3 on 2022-11-22 21:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.upload_profile_image,
                verbose_name="Profile image",
            ),
        ),
    ]
